[build]
  command = """
    wget https://go.dev/dl/go1.22.6.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.22.6.linux-amd64.tar.gz
    export PATH=$PATH:/usr/local/go/bin
    go version
    chmod +x ./tailwindcss
    go mod download
    make build-netlify
  """
  publish = "public"