[build]
  command = """
    chmod +x ./tailwindcss
    go mod download
    go install github.com/a-h/templ/cmd/templ@latest
    export PATH=$PATH:$(go env GOPATH)/bin
    make build-netlify
    cp -r static public/
    cp static/favicon.ico public/favicon.ico
    go get github.com/aws/aws-lambda-go/events
    go get github.com/aws/aws-lambda-go/lambda
    go build -o functions/print ./functions/print.go
  """
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/print"
  to = "/.netlify/functions/print"
  status = 200