[build]
  command = """
    chmod +x ./tailwindcss
    go mod download
    go install github.com/a-h/templ/cmd/templ@latest
    export PATH=$PATH:$(go env GOPATH)/bin
    make build-netlify
    cp -r static public/
  """
  publish = "public"